networks:
  lnmp:
    driver: bridge

services:
  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    ports:
      - 80:80
    volumes:
      - ./src/public:/var/www/html/public
    networks:
      - lnmp

  php:
    build:
      context: .
      dockerfile: php/Dockerfile
    networks:
      - lnmp
    volumes:
      - ./src:/var/www/html
    depends_on:
      - mysql

  mysql:
    image: mysql:8.1.0
    environment:
      - MYSQL_DATABASE=testdb
      - MYSQL_USER=user
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=secret
    ports:
      - 3306:3306
    volumes:
      - ./db:/var/lib/mysql
    networks:
      - lnmp
